export const dataSource = [
  { key: "1", name: "Mike", age: 32, address: "10 Downing Street" },
  { key: "2", name: "John", age: 42, address: "10 Downing Street" },
  { key: "3", name: "Sarah", age: 28, address: "221B Baker Street" },
  { key: "4", name: "Emily", age: 35, address: "742 Evergreen Terrace" },
  { key: "5", name: "David", age: 45, address: "1600 Pennsylvania Avenue" },
  { key: "6", name: "Jessica", age: 31, address: "350 Fifth Avenue" },
  { key: "7", name: "Robert", age: 39, address: "405 Lexington Avenue" },
  { key: "8", name: "Linda", age: 27, address: "890 Fifth Avenue" },
  { key: "9", name: "William", age: 50, address: "123 Maple Street" },
  { key: "10", name: "Barbara", age: 33, address: "456 Oak Avenue" },
  { key: "11", name: "Richard", age: 41, address: "789 Pine Road" },
  { key: "12", name: "Susan", age: 29, address: "101 Cedar Lane" },
  { key: "13", name: "Thomas", age: 37, address: "202 Birch Court" },
  { key: "14", name: "Margaret", age: 44, address: "303 Walnut Way" },
  { key: "15", name: "Christopher", age: 30, address: "404 Elm Drive" },
  { key: "16", name: "Dorothy", age: 52, address: "505 Ash Street" },
  { key: "17", name: "Daniel", age: 26, address: "606 Spruce Boulevard" },
  { key: "18", name: "Lisa", age: 34, address: "707 Willow Place" },
  { key: "19", name: "Paul", age: 48, address: "808 Poplar Circle" },
  { key: "20", name: "Nancy", age: 36, address: "909 Juniper Lane" },
  { key: "21", name: "Mark", age: 43, address: "111 Cherry Street" },
  { key: "22", name: "Karen", age: 25, address: "222 Magnolia Ave" },
  { key: "23", name: "George", age: 55, address: "333 Sycamore Dr" },
  { key: "24", name: "Betty", age: 38, address: "444 Hickory Ln" },
  { key: "25", name: "Kenneth", age: 47, address: "555 Redwood Hwy" },
  { key: "26", name: "Helen", age: 31, address: "666 Aspen Way" },
  { key: "27", name: "Steven", age: 40, address: "777 Dogwood Dr" },
  { key: "28", name: "Sandra", age: 29, address: "888 Laurel St" },
  { key: "29", name: "Edward", age: 51, address: "999 Palm Blvd" },
  { key: "30", name: "Donna", age: 33, address: "123 Bayside Dr" },
];

export const columns = [
  {
    title: "Number",
    dataIndex: "key",
    key: "key",
  },
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
  },
  {
    title: "Address",
    dataIndex: "address",
    key: "address",
  },
];
